# Coloque a Organization e a Project Key que você copiou do SonarCloud
sonar.organization=kellytacardosoleal1-design
sonar.projectKey=kellytacardosoleal1-design_open-color
sonar.projectName=open-color

# Onde está o código do projeto (geralmente é na raiz '.' ou dentro de uma pasta 'src')
sonar.sources=.

# Extensões ou pastas que você quer excluir da análise (ex: node_modules, pastas de build)
sonar.exclusions=**/node_modules/**, **/bower_components/**, **/dist/**, **/build/**

# Caminho para o relatório de cobertura de testes (fundamental para validar os 85% do professor!)
# Se o projeto for JavaScript/TypeScript, geralmente usa o lcov:
sonar.javascript.lcov.reportPaths=coverage/lcov.info
