# Seus dados do SonarCloud (Lyan)
sonar.organization=lyan-araguaia
sonar.projectKey=lyan-araguaia_open-color-teste-lyan
sonar.projectName=open-color-teste-lyan

# Onde está o código do projeto
sonar.sources=.

# Exclusões para não inflar a contagem de linhas desnecessariamente
sonar.exclusions=**/node_modules/**, **/bower_components/**, **/dist/**, **/build/**, **/*.test.js, **/*.spec.js

# Caminho para o relatório de cobertura de testes do Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info