sonar.organization=magaly8020
sonar.projectKey=magaly8020_open-color-teste-lyan
sonar.projectName=open-color-teste-lyan
sonar.host.url=https://sonarcloud.io

sonar.sources=.

# EXCLUSÃO COMPLETA: Bloqueia dependências externas, testes e arquivos duplicados
sonar.exclusions=node_modules/**, public/**, tests/**, builder/**, coverage/**, **/*.test.js, compile-templates.js, open-color.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info